[package]
name = "image_downloader"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.22", features = ["blocking", "json"] }
regex = "1.9"
clap = { version = "4.4", features = ["derive"] }